// Generated by CoffeeScript 1.6.2
var _this = this;

suite("Test the Filter-Area with differnt init options", function() {
  suite("Nothing set", function() {
    setup(function() {
      var Option;

      Option = {};
      return FB.init(Option);
    });
    teardown(function() {
      var clear;

      clear = document.getElementById("FB");
      return document.body.removeChild(clear);
    });
    return test("No Filter-Area there => OK", function() {
      var actual;

      actual = config.container();
      return assert.that("#" + actual, has.no.tag("#filter"));
    });
  });
  return suite("Filter=TRUE", function() {
    setup(function() {
      var Option;

      Option = {};
      Option.filter = true;
      return FB.init(Option);
    });
    teardown(function() {
      var clear;

      clear = document.getElementById("FB");
      if (clear) {
        return document.body.removeChild(clear);
      }
    });
    test("Filter-Area there => OK", function() {
      var actual;

      actual = config.container();
      return assert.that("#" + actual, has.tag("#filter"));
    });
    test("Filter has an search input", function() {
      return assert.that("#filter", has.tag("#filterSearch"));
    });
    return suite("Categories = TRUE", function() {
      setup(function() {
        var Option;

        Option = {};
        Option.filter = true;
        Option.filter = "FB";
        Option.categories = ["one", "two"];
        return FB.init(Option);
      });
      teardown(function() {
        var clear;

        clear = document.getElementById("FB");
        if (clear) {
          return document.body.removeChild(clear);
        }
      });
      test("Category - Selection exist", function() {
        return assert.that("#filter", has.tag("#catFilter"));
      });
      test("Checkbox for 'one' exist", function() {
        return assert.that("#catFilter", has.tag("#catFilter_one"));
      });
      return test("Checkbox for 'two' exist", function() {
        return assert.that("#catFilter", has.tag("#catFilter_two"));
      });
    });
  });
});
